// go:generate go run core/gen.go core/commands_gen.go
//+build ignore

package main

import (
	"io/ioutil"
	"os"
	"strings"
	"text/template"
)

func main() {
	bytesCommandsJSON, err := ioutil.ReadFile("commands.json")
	if err != nil {
		panic(err)
	}
	bytesCommandsTemplate, err := ioutil.ReadFile("commands.go")
	if err != nil {
		panic(err)
	}
	commandsTemplate := strings.Replace(string(bytesCommandsTemplate), "// +build ignore", "// This file was autogenerated. DO NOT EDIT.", 1)
	commandsJSON := strings.TrimSuffix(string(bytesCommandsJSON), "\n")
	params := struct{ CommandsJSON string }{CommandsJSON: commandsJSON}

	out, err := os.Create("commands_gen.go")
	if err != nil {
		panic(err)
	}
	tpl, err := template.New("commands_gen.go").Parse(commandsTemplate)
	if err != nil {
		panic(err)
	}
	err = tpl.Execute(out, params)
	if err != nil {
		panic(err)
	}
}
