// +build ignore

package main

import (
	"io/ioutil"
	"os"
	"strings"
	"text/template"
)

const (
	commandsTemplatePath = "core/commands.go"
	commandsJsonPath     = "core/commands.json"
	commandsGenPath      = "core/commands_gen.go"
)

func main() {
	bytesCommandsJSON, err := ioutil.ReadFile(commandsJsonPath)
	if err != nil {
		panic(err)
	}
	bytesCommandsTemplate, err := ioutil.ReadFile(commandsTemplatePath)
	if err != nil {
		panic(err)
	}
	commandsTemplate := strings.Replace(string(bytesCommandsTemplate), "// +build ignore", "// This file was autogenerated. DO NOT EDIT.", 1)
	commandsJSON := strings.TrimSuffix(string(bytesCommandsJSON), "\n")
	params := struct{ CommandsJSON string }{CommandsJSON: commandsJSON}

	out, err := os.Create(commandsGenPath)
	if err != nil {
		panic(err)
	}
	tpl, err := template.New(commandsGenPath).Parse(commandsTemplate)
	if err != nil {
		panic(err)
	}
	err = tpl.Execute(out, params)
	if err != nil {
		panic(err)
	}
}
